In [1]:
import pandas as pd
pd.set_option('display.max_columns', 500)

In [2]:
import pickle

file_path = './results.pkl'
with open(file_path, "rb") as fh:
  results_df = pickle.load(fh)

results_df.columns = ['dataset', 'random_seed', 'train_f1_micro', 'train_f1_macro', 'train_accuracy', 'classification_report']
results_df.head()

,dataset,random_seed,train_f1_micro,train_f1_macro,train_accuracy,classification_report
0,whole_merged.pkl,0,0.952693,0.908480,0.952693,precision recall f1-score ...
1,sum_merged.pkl,0,0.940320,0.888230,0.940320,precision recall f1-score ...
2,avg_merged.pkl,0,0.955604,0.913433,0.955604,precision recall f1-score ...
3,whole_merged.pkl,1,0.944687,0.895234,0.944687,precision recall f1-score ...
4,sum_merged.pkl,1,0.926492,0.866987,0.926492,precision recall f1-score ...

In [3]:
# parse dataset name
results_df.dataset = [x.split('/')[-1].split('.')[0] for x in results_df.dataset]
results_df.classification_report = [x.split() for x in results_df.classification_report]
results_df.head()

,dataset,random_seed,train_f1_micro,train_f1_macro,train_accuracy,classification_report
0,whole_merged,0,0.952693,0.908480,0.952693,"[precision, recall, f1-score, support, 0, 0.94..."
1,sum_merged,0,0.940320,0.888230,0.940320,"[precision, recall, f1-score, support, 0, 0.95..."
2,avg_merged,0,0.955604,0.913433,0.955604,"[precision, recall, f1-score, support, 0, 0.94..."
3,whole_merged,1,0.944687,0.895234,0.944687,"[precision, recall, f1-score, support, 0, 0.96..."
4,sum_merged,1,0.926492,0.866987,0.926492,"[precision, recall, f1-score, support, 0, 0.96..."

In [4]:
# parse classification report
results_df['precision_0'] = [float(x[5]) for x in results_df.classification_report]
results_df['recall_0'] = [float(x[6]) for x in results_df.classification_report]
results_df['f1_score_0'] = [float(x[7]) for x in results_df.classification_report]

results_df['precision_1'] = [float(x[10]) for x in results_df.classification_report]
results_df['recall_1'] = [float(x[11]) for x in results_df.classification_report]
results_df['f1_score_1'] = [float(x[12]) for x in results_df.classification_report]

results_df['accuracy'] = [float(x[15]) for x in results_df.classification_report]

results_df['precision_macro_avg'] = [float(x[19]) for x in results_df.classification_report]
results_df['recall_macro_avg'] = [float(x[20]) for x in results_df.classification_report]
results_df['f1_score_macro_avg'] = [float(x[21]) for x in results_df.classification_report]

results_df['precision_weighted_avg'] = [float(x[25]) for x in results_df.classification_report]
results_df['recall_weighted_avg'] = [float(x[26]) for x in results_df.classification_report]
results_df['f1_score_weighted_avg'] = [float(x[27]) for x in results_df.classification_report]

results_df.drop(columns=['classification_report'], inplace=True)

results_df.head()

,dataset,random_seed,train_f1_micro,train_f1_macro,train_accuracy,precision_0,recall_0,f1_score_0,precision_1,recall_1,f1_score_1,accuracy,precision_macro_avg,recall_macro_avg,f1_score_macro_avg,precision_weighted_avg,recall_weighted_avg,f1_score_weighted_avg
0,whole_merged,0,0.952693,0.908480,0.952693,0.94,0.91,0.93,0.51,0.61,0.56,0.88,0.73,0.76,0.74,0.89,0.88,0.88
1,sum_merged,0,0.940320,0.888230,0.940320,0.95,0.86,0.90,0.41,0.66,0.51,0.84,0.68,0.76,0.71,0.88,0.84,0.85
2,avg_merged,0,0.955604,0.913433,0.955604,0.94,0.89,0.91,0.44,0.59,0.50,0.85,0.69,0.74,0.71,0.87,0.85,0.86
3,whole_merged,1,0.944687,0.895234,0.944687,0.96,0.92,0.94,0.57,0.75,0.65,0.90,0.77,0.83,0.79,0.91,0.90,0.90
4,sum_merged,1,0.926492,0.866987,0.926492,0.96,0.90,0.93,0.51,0.73,0.60,0.88,0.73,0.81,0.76,0.90,0.88,0.88

In [5]:
results_df.describe()

,train_f1_micro,train_f1_macro,train_accuracy,precision_0,recall_0,f1_score_0,precision_1,recall_1,f1_score_1,accuracy,precision_macro_avg,recall_macro_avg,f1_score_macro_avg,precision_weighted_avg,recall_weighted_avg,f1_score_weighted_avg
count,153.000000,153.000000,153.000000,153.000000,153.000000,153.000000,153.000000,153.000000,153.000000,153.000000,153.000000,153.000000,153.000000,153.000000,153.000000,153.000000
mean,0.944716,0.895622,0.944716,0.959673,0.910392,0.934314,0.550261,0.738105,0.628758,0.888431,0.755098,0.824118,0.781176,0.907712,0.888431,0.894967
std,0.009316,0.014923,0.009316,0.010287,0.017840,0.010623,0.051720,0.067119,0.048250,0.016588,0.028840,0.033805,0.029063,0.013104,0.016588,0.015005
min,0.921397,0.859495,0.921397,0.930000,0.860000,0.900000,0.410000,0.550000,0.500000,0.840000,0.680000,0.730000,0.700000,0.870000,0.840000,0.850000
25%,0.936681,0.882505,0.936681,0.950000,0.900000,0.930000,0.520000,0.700000,0.600000,0.880000,0.740000,0.810000,0.760000,0.900000,0.880000,0.890000
50%,0.946870,0.898794,0.946870,0.960000,0.910000,0.930000,0.550000,0.750000,0.630000,0.890000,0.750000,0.830000,0.780000,0.910000,0.890000,0.890000
75%,0.952693,0.908480,0.952693,0.970000,0.920000,0.940000,0.580000,0.770000,0.660000,0.900000,0.770000,0.850000,0.800000,0.920000,0.900000,0.900000
max,0.959243,0.919731,0.959243,0.980000,0.960000,0.960000,0.720000,0.890000,0.740000,0.930000,0.840000,0.900000,0.850000,0.940000,0.930000,0.930000

In [ ]:
columns = ['f1_score_1', 'precision_1', 'recall_1', 'accuracy']

In [7]:
results_df.groupby(by=['dataset'])[columns].describe(percentiles=[])

             f1_score_1                                       precision_1  \
                  count      mean       std   min   50%   max       count
dataset
avg_merged         51.0  0.640784  0.047533  0.50  0.64  0.74        51.0
sum_merged         51.0  0.621373  0.044046  0.51  0.62  0.71        51.0
whole_merged       51.0  0.624118  0.051504  0.50  0.63  0.73        51.0

                                                   recall_1            \
                  mean       std   min   50%   max    count      mean
dataset
avg_merged    0.571961  0.047540  0.44  0.56  0.71     51.0  0.730784
sum_merged    0.526078  0.046047  0.41  0.52  0.63     51.0  0.765294
whole_merged  0.552745  0.051656  0.44  0.55  0.72     51.0  0.718235

                                         accuracy                            \
                   std   min   50%   max    count      mean       std   min
dataset
avg_merged    0.066056  0.59  0.73  0.89     51.0  0.895490  0.014327  0.85
sum_merged    0.057214  0.64  0.77  0.89     51.0  0.880588  0.015800  0.84
whole_merged  0.069619  0.55  0.73  0.84     51.0  0.889216  0.016352  0.85

                         f1_score_macro_avg                                  \
               50%   max              count      mean       std   min   50%
dataset
avg_merged    0.89  0.93               51.0  0.789608  0.026979  0.71  0.79
sum_merged    0.88  0.92               51.0  0.774902  0.027157  0.71  0.77
whole_merged  0.89  0.93               51.0  0.779020  0.031385  0.70  0.78


               max
dataset
avg_merged    0.85
sum_merged    0.83
whole_merged  0.85

In [8]:
results_df.groupby(by=['dataset']).describe(percentiles=[])

             train_f1_micro                                                    \
                      count      mean       std       min       50%       max
dataset
avg_merged             51.0  0.951009  0.004197  0.941776  0.951965  0.959243
sum_merged             51.0  0.933499  0.005720  0.921397  0.932314  0.946870
whole_merged           51.0  0.949639  0.004477  0.938137  0.949782  0.957060

             train_f1_macro                                                    \
                      count      mean       std       min       50%       max
dataset
avg_merged             51.0  0.905723  0.007023  0.890548  0.907253  0.919731
sum_merged             51.0  0.877696  0.008854  0.859495  0.875765  0.898794
whole_merged           51.0  0.903446  0.007416  0.884783  0.903601  0.915938

             train_accuracy                                                    \
                      count      mean       std       min       50%       max
dataset
avg_merged             51.0  0.951009  0.004197  0.941776  0.951965  0.959243
sum_merged             51.0  0.933499  0.005720  0.921397  0.932314  0.946870
whole_merged           51.0  0.949639  0.004477  0.938137  0.949782  0.957060

             precision_0                                       recall_0  \
                   count      mean       std   min   50%   max    count
dataset
avg_merged          51.0  0.959804  0.010098  0.94  0.96  0.98     51.0
sum_merged          51.0  0.962941  0.009010  0.94  0.96  0.98     51.0
whole_merged        51.0  0.956275  0.010763  0.93  0.96  0.98     51.0

                                                   f1_score_0            \
                  mean       std   min   50%   max      count      mean
dataset
avg_merged    0.919412  0.013328  0.89  0.92  0.95       51.0  0.938627
sum_merged    0.897059  0.016161  0.86  0.89  0.93       51.0  0.929412
whole_merged  0.914706  0.015666  0.88  0.91  0.96       51.0  0.934902

                                         precision_1                      \
                   std   min   50%   max       count      mean       std
dataset
avg_merged    0.009802  0.91  0.94  0.96        51.0  0.571961  0.047540
sum_merged    0.009882  0.90  0.93  0.95        51.0  0.526078  0.046047
whole_merged  0.010271  0.91  0.94  0.96        51.0  0.552745  0.051656

                               recall_1                                        \
               min   50%   max    count      mean       std   min   50%   max
dataset
avg_merged    0.44  0.56  0.71     51.0  0.730784  0.066056  0.59  0.73  0.89
sum_merged    0.41  0.52  0.63     51.0  0.765294  0.057214  0.64  0.77  0.89
whole_merged  0.44  0.55  0.72     51.0  0.718235  0.069619  0.55  0.73  0.84

             f1_score_1                                       accuracy  \
                  count      mean       std   min   50%   max    count
dataset
avg_merged         51.0  0.640784  0.047533  0.50  0.64  0.74     51.0
sum_merged         51.0  0.621373  0.044046  0.51  0.62  0.71     51.0
whole_merged       51.0  0.624118  0.051504  0.50  0.63  0.73     51.0

                                                   precision_macro_avg  \
                  mean       std   min   50%   max               count
dataset
avg_merged    0.895490  0.014327  0.85  0.89  0.93                51.0
sum_merged    0.880588  0.015800  0.84  0.88  0.92                51.0
whole_merged  0.889216  0.016352  0.85  0.89  0.93                51.0

                                                   recall_macro_avg            \
                  mean       std   min   50%   max            count      mean
dataset
avg_merged    0.765490  0.027152  0.69  0.76  0.84             51.0  0.825098
sum_merged    0.744118  0.026471  0.68  0.74  0.80             51.0  0.831373
whole_merged  0.755686  0.029275  0.69  0.76  0.84             51.0  0.815882

                                         f1_score_macro_avg            \
                   std   min   50%   max              count      mean
dataset
avg_merged    0.033904  0.74  0.82  0.90               51.0  0.789608
sum_merged    0.030661  0.76  0.83  0.89               51.0  0.774902
whole_merged  0.035506  0.73  0.82  0.88               51.0  0.779020

                                         precision_weighted_avg            \
                   std   min   50%   max                  count      mean
dataset
avg_merged    0.026979  0.71  0.79  0.85                   51.0  0.910000
sum_merged    0.027157  0.71  0.77  0.83                   51.0  0.908039
whole_merged  0.031385  0.70  0.78  0.85                   51.0  0.905098

                                         recall_weighted_avg            \
                   std   min   50%   max               count      mean
dataset
avg_merged    0.013266  0.87  0.91  0.94                51.0  0.895490
sum_merged    0.011835  0.88  0.91  0.93                51.0  0.880588
whole_merged  0.013910  0.87  0.91  0.93                51.0  0.889216

                                         f1_score_weighted_avg            \
                   std   min   50%   max                 count      mean
dataset
avg_merged    0.014327  0.85  0.89  0.93                  51.0  0.900196
sum_merged    0.015800  0.84  0.88  0.92                  51.0  0.889608
whole_merged  0.016352  0.85  0.89  0.93                  51.0  0.895098


                   std   min   50%   max
dataset
avg_merged    0.013340  0.86  0.90  0.93
sum_merged    0.014417  0.85  0.89  0.92
whole_merged  0.015540  0.86  0.90  0.93